# MIT License
#
# Copyright (c) 2026 LONGZR007
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

CC = gcc
CFLAGS = -Wall -Wextra -O2 -g -pthread
INCLUDES = -I../../inc -I.
LIBS = -lpthread

SRCS = ../../src/eproto.c \
       ../../src/eproto_crc16.c \
       ../../src/eproto_frame_parser.c \
       ../../src/eproto_packet_node.c \
       ../../src/eproto_ring_buffer.c \
       ../../src/eproto_upper.c

SENDER_SRCS = sender.c common_serial.c $(SRCS)
RECEIVER_SRCS = receiver.c common_serial.c $(SRCS)

SENDER_TARGET = file_transfer_sender
RECEIVER_TARGET = file_transfer_receiver

.PHONY: all clean

all: $(SENDER_TARGET) $(RECEIVER_TARGET)

$(SENDER_TARGET): $(SENDER_SRCS)
	$(CC) $(CFLAGS) $(INCLUDES) -o $@ $^ $(LIBS)

$(RECEIVER_TARGET): $(RECEIVER_SRCS)
	$(CC) $(CFLAGS) $(INCLUDES) -o $@ $^ $(LIBS)

clean:
	rm -f $(SENDER_TARGET) $(RECEIVER_TARGET) received_file.bin
